# roles/install_csi_driver/tasks/main.yml
---
  - name: add nutanix csi helm repo
    kubernetes.core.helm_repository:
      name: nutanix
      repo_url: "{{ nutanix_helm_repo_url }}"

  - name: generate helm chart values file
    template:
      src: templates/nutanix_csi_values.yaml
      dest: ~/.nutanix_csi_values.yaml
      owner: nutanix
      group: nutanix
      mode: '0600'

  - name: install nutanix csi helm chart using values file
    kubernetes.core.helm:
      name: nutanix-csi
      release_namespace: "{{ namespace }}"
      create_namespace: true
      chart_ref: "{{ chart_ref }}"
      wait: yes
      state: present
      values_files:
        - ~/.nutanix_csi_values.yaml

  # - name: install nutanix csi driver object
  #   kubernetes.core.k8s:
  #     state: present
  #     src: "{{ lookup('template', 'csi_driver_object.yaml') | from_yaml }}"
  #
  # - name: install nutanix csi driver secret
  #   kubernetes.core.k8s:
  #     state: present
  #     src: "{{ lookup('template', 'secret.yaml') | from_yaml }}"
  #
  # - name: install nutanix csi driver rbac
  #   kubernetes.core.k8s:
  #     state: present
  #     src: "https://github.com/nutanix/csi-plugin/blob/master/deploy/ntnx-csi-rbac.yaml"
  #
  # - name: install nutanix csi driver node
  #   kubernetes.core.k8s:
  #     state: present
  #     src: "https://github.com/nutanix/csi-plugin/blob/master/deploy/ntnx-csi-node.yaml"
  #
  # - name: install nutanix csi driver provisioner
  #   kubernetes.core.k8s:
  #     state: present
  #     src: "https://github.com/nutanix/csi-plugin/blob/master/deploy/ntnx-csi-provisioner.yaml"
  #
  # - name: create nutanix storage class
  #   kubernetes.core.k8s:
  #     state: present
  #     src: "{{ lookup('template', 'storage_class.yaml') | from_yaml }}"
