# roles/install_csi_driver/tasks/main.yml
---
  - name: add nutanix csi helm repo
    kubernetes.core.helm_repository:
      name: nutanix
      repo_url: "{{ nutanix_helm_repo_url }}"

  - name: install nutanix csi helm chart
    kubernetes.core.helm:
      name: nutanix-csi
      release_namespace: "{{ namespace }}"
      create_namespace: true
      chart_ref: "{{ chart_ref }}"
      wait: yes
      state: present
      values: "{{ lookup('template', 'nutanix_csi_values.yaml') | from_yaml }}"
