# roles/install_csi_driver/defaults/main.yml
nutanix_helm_repo_url: "https://nutanix.github.io/helm/"
namespace: "kube-system"
chart_ref: "nutanix/nutanix-csi-storage"

# csi driver default values
legacy: false
os: none
volumeClass: false
kubeletDir: "/var/lib/kubelet"
nodeSelector: {}
tolerations: []
imagePullPolicy: IfNotPresent
volumeClassName: nutanix-volume
fileClass: false
fileClassName: nutanix-file
dynamicFileClass: false
dynamicFileClassName: nutanix-dynamicfile
defaultStorageClass: none
prismEndPoint: "10.0.0.1"
username: "admin"
password: "nutanix/4u"
secretName: ntnx-secret
createSecret: true
storageContainer: default
fsType: "xfs"
lvmVolume: false
lvmDisks: 4
networkSegmentation: false
fileHost: 10.0.0.3
filePath: share
fileServerName: file
