# roles/install_csi_driver/defaults/main.yml
nutanix_helm_repo_url: "https://nutanix.github.io/helm/"
namespace: "kube-system"
chart_ref: "nutanix/nutanix-csi-storage"

# csi driver default values
defaultStorageClass: none
#prism:
prismEndPoint: ""
username: "admin"
password: ""
secretName: "ntnx-secret"
createSecret: true
storageContainer: "default"

# volumes:
volumeClass: false
volumeClassName: "nutanix-volume"
networkSegmentation: false
fsType: "xfs"
lvmVolume: false
lvmDisks: 4

# files:
fileClass: false
fileClassName: "nutanix-file"
dynamicFileClass: false
dynamicFileClassName: nutanix-dynamicfile
fileHost: ""
filePath: ""
fileServerName: ""

# CSI Driver Defaults
legacy: false
os: none
kubeletDir: "/var/lib/kubelet"
nodeSelector: {}
tolerations: []
imagePullPolicy: IfNotPresent
servicemonitor:
  enabled: false
